export const TYPES = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    LOADING: 'LOADING',
    UPDATE: "UPDATE",
    CHANGESTATUS: "CHANGESTATUS",
    ADDCANCELATION: "ADDCANCELATION",
    UPDATEMESSAGE: "UPDATEMESSAGE"
}