export const TYPES = {
    ADDNEWPOST: "ADDNEWPOST",
    GETPOSTS: "GETPOSTS",
    GETPENDINGPOSTS: "GETPENDINGPOSTS",
    CLEARALERTMSG: "CLEARALERTMSG",
    UPDATEPOST: "UPDATEPOST",
    ADDOFFERINPOST:"ADDOFFERINPOST",
    ADDMESSAGE:"ADDMESSAGE",
    UPDATEMYSTATUS:"UPDATEMYSTATUS",
    LOADING: 'LOADING',
}